//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations.AnimalWorld {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnimalWorldReservations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimalWorldReservations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.AnimalWorld.AnimalWorldReservations", typeof(AnimalWorldReservations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked.
        /// </summary>
        public static string Booked {
            get {
                return ResourceManager.GetString("Booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking successfully completed!.
        /// </summary>
        public static string BookingCompleted {
            get {
                return ResourceManager.GetString("BookingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book now.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets from different sections of the site are collected here..
        /// </summary>
        public static string DifferentTickets {
            get {
                return ResourceManager.GetString("DifferentTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My tickets.
        /// </summary>
        public static string MyTickets {
            get {
                return ResourceManager.GetString("MyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reservation is not available.
        /// </summary>
        public static string NoBooked {
            get {
                return ResourceManager.GetString("NoBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tickets purchased.
        /// </summary>
        public static string NoTickets {
            get {
                return ResourceManager.GetString("NoTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present the QR code at the entrance to the zoo.
        /// </summary>
        public static string PresentQr {
            get {
                return ResourceManager.GetString("PresentQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR-code.
        /// </summary>
        public static string Qr {
            get {
                return ResourceManager.GetString("Qr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reservation failed.
        /// </summary>
        public static string ReservationFailed {
            get {
                return ResourceManager.GetString("ReservationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visit is booked.
        /// </summary>
        public static string VisitBooked {
            get {
                return ResourceManager.GetString("VisitBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your zoo visit is booked. Your ticket is valid for one month. Please use the first name, last name, and phone number from your account to purchase your ticket..
        /// </summary>
        public static string VisitBookedCompleteMessage {
            get {
                return ResourceManager.GetString("VisitBookedCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to continue your booking. To book, you must complete your profile: first name, last name, and phone number. Please try again after updating your profile information..
        /// </summary>
        public static string VisitBookedDenyMessage {
            get {
                return ResourceManager.GetString("VisitBookedDenyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of visit: before.
        /// </summary>
        public static string VisitDate {
            get {
                return ResourceManager.GetString("VisitDate", resourceCulture);
            }
        }
    }
}
