//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations.AnimalWorld {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnimalWorldAnimalFamily {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimalWorldAnimalFamily() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.AnimalWorld.AnimalWorldAnimalFamily", typeof(AnimalWorldAnimalFamily).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding an animal family.
        /// </summary>
        public static string AddAnimalFamily {
            get {
                return ResourceManager.GetString("AddAnimalFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal families.
        /// </summary>
        public static string AnimalFamilies {
            get {
                return ResourceManager.GetString("AnimalFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family of animal.
        /// </summary>
        public static string AnimalFamily {
            get {
                return ResourceManager.GetString("AnimalFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: Bears.
        /// </summary>
        public static string AnimalFamilyExample {
            get {
                return ResourceManager.GetString("AnimalFamilyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key features of the family....
        /// </summary>
        public static string AnimalFamilySummary {
            get {
                return ResourceManager.GetString("AnimalFamilySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the animal family.
        /// </summary>
        public static string ChooseAnimalFamily {
            get {
                return ResourceManager.GetString("ChooseAnimalFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        public static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the information about the new animal family.
        /// </summary>
        public static string FillInformation {
            get {
                return ResourceManager.GetString("FillInformation", resourceCulture);
            }
        }
    }
}
