//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations.AnimalWorld {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnimalWorldPromotions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimalWorldPromotions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.AnimalWorld.AnimalWorldPromotions", typeof(AnimalWorldPromotions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no promotions running at the moment.
        /// </summary>
        public static string NoPromotions {
            get {
                return ResourceManager.GetString("NoPromotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        public static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special offers for visitors to our zoos.
        /// </summary>
        public static string SpecialOffers {
            get {
                return ResourceManager.GetString("SpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay tuned for more exciting offers coming soon!.
        /// </summary>
        public static string StayTuned {
            get {
                return ResourceManager.GetString("StayTuned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        public static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
    }
}
