//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations.AnimalWorld {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnimalWorldAddData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimalWorldAddData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.AnimalWorld.AnimalWorldAddData", typeof(AnimalWorldAddData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding animal data.
        /// </summary>
        public static string AddingAnimalData {
            get {
                return ResourceManager.GetString("AddingAnimalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding data.
        /// </summary>
        public static string AddingData {
            get {
                return ResourceManager.GetString("AddingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a new genus of animals.
        /// </summary>
        public static string AddingGenus {
            get {
                return ResourceManager.GetString("AddingGenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new animal species.
        /// </summary>
        public static string AddingSpecies {
            get {
                return ResourceManager.GetString("AddingSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a promotion.
        /// </summary>
        public static string AddPromotion {
            get {
                return ResourceManager.GetString("AddPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new zoo to the database.
        /// </summary>
        public static string AddZoo {
            get {
                return ResourceManager.GetString("AddZoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate animal species with the zoos where they live.
        /// </summary>
        public static string Associate {
            get {
                return ResourceManager.GetString("Associate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biological data: families, species and their habitats.
        /// </summary>
        public static string BiologicalData {
            get {
                return ResourceManager.GetString("BiologicalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.
        /// </summary>
        public static string Infrastructure {
            get {
                return ResourceManager.GetString("Infrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select what information you want to add.
        /// </summary>
        public static string SelectInformationType {
            get {
                return ResourceManager.GetString("SelectInformationType", resourceCulture);
            }
        }
    }
}
