//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations.AnimalWorld {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnimalWorldIndex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimalWorldIndex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.AnimalWorld.AnimalWorldIndex", typeof(AnimalWorldIndex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About our planet.
        /// </summary>
        public static string AboutPlanet {
            get {
                return ResourceManager.GetString("AboutPlanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal World.
        /// </summary>
        public static string AnimalWorldTitle {
            get {
                return ResourceManager.GetString("AnimalWorldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected families?.
        /// </summary>
        public static string ConfirmDeleteSelected {
            get {
                return ResourceManager.GetString("ConfirmDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no animal families.
        /// </summary>
        public static string EmptyStateNoFamilies {
            get {
                return ResourceManager.GetString("EmptyStateNoFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Earth is home to millions of amazing creatures, from tiny insects to giant blue whales.
        /// </summary>
        public static string IndexDescription {
            get {
                return ResourceManager.GetString("IndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data on animal families yet.
        /// </summary>
        public static string NoAnimalFamilies {
            get {
                return ResourceManager.GetString("NoAnimalFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data on animal species yet.
        /// </summary>
        public static string NoAnimalSpecies {
            get {
                return ResourceManager.GetString("NoAnimalSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the cards to select multiple families.
        /// </summary>
        public static string SelectionHint {
            get {
                return ResourceManager.GetString("SelectionHint", resourceCulture);
            }
        }
    }
}
