//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations.AnimalWorld {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnimalWorldFacts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimalWorldFacts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.AnimalWorld.AnimalWorldFacts", typeof(AnimalWorldFacts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesting facts about animals.
        /// </summary>
        public static string AnimalFacts {
            get {
                return ResourceManager.GetString("AnimalFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery of animals.
        /// </summary>
        public static string AnimalsGallery {
            get {
                return ResourceManager.GetString("AnimalsGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an interesting fact....
        /// </summary>
        public static string EnterFact {
            get {
                return ResourceManager.GetString("EnterFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact.
        /// </summary>
        public static string Fact {
            get {
                return ResourceManager.GetString("Fact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gallery is temporarily empty.
        /// </summary>
        public static string GalleryEmpty {
            get {
                return ResourceManager.GetString("GalleryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesting facts.
        /// </summary>
        public static string InterestingFacts {
            get {
                return ResourceManager.GetString("InterestingFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known facts.
        /// </summary>
        public static string KnownFacts {
            get {
                return ResourceManager.GetString("KnownFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn amazing facts about different types of animals.
        /// </summary>
        public static string LearnFacts {
            get {
                return ResourceManager.GetString("LearnFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading facts.
        /// </summary>
        public static string LoadingFacts {
            get {
                return ResourceManager.GetString("LoadingFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we couldn&apos;t load the images. Please try refreshing the page later..
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text of a fact.
        /// </summary>
        public static string TextFact {
            get {
                return ResourceManager.GetString("TextFact", resourceCulture);
            }
        }
    }
}
