//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations.AnimalWorld {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnimalWorldAnimalSpecies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimalWorldAnimalSpecies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.AnimalWorld.AnimalWorldAnimalSpecies", typeof(AnimalWorldAnimalSpecies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding an animal species.
        /// </summary>
        public static string AddAnimalSpecies {
            get {
                return ResourceManager.GetString("AddAnimalSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All columns.
        /// </summary>
        public static string AllColumns {
            get {
                return ResourceManager.GetString("AllColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal species.
        /// </summary>
        public static string AnimalSpecies {
            get {
                return ResourceManager.GetString("AnimalSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: Brown bear.
        /// </summary>
        public static string AnimalSpeciesExample {
            get {
                return ResourceManager.GetString("AnimalSpeciesExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the species.
        /// </summary>
        public static string AnimalSpeciesSummary {
            get {
                return ResourceManager.GetString("AnimalSpeciesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is how the card will look on the website.
        /// </summary>
        public static string CardLook {
            get {
                return ResourceManager.GetString("CardLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog of animal species of our world.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the animal type.
        /// </summary>
        public static string ChooseAnimalSpecies {
            get {
                return ResourceManager.GetString("ChooseAnimalSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitat.
        /// </summary>
        public static string Habitat {
            get {
                return ResourceManager.GetString("Habitat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vast areas of forest and mountain zones of the Northern Hemisphere.
        /// </summary>
        public static string HabitatExample {
            get {
                return ResourceManager.GetString("HabitatExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found. Try changing your search query.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal species.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in column.
        /// </summary>
        public static string SearchColumn {
            get {
                return ResourceManager.GetString("SearchColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search query.
        /// </summary>
        public static string SearchQuery {
            get {
                return ResourceManager.GetString("SearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species name.
        /// </summary>
        public static string SpeciesName {
            get {
                return ResourceManager.GetString("SpeciesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to search....
        /// </summary>
        public static string TextToSearch {
            get {
                return ResourceManager.GetString("TextToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to till.
        /// </summary>
        public static string Till {
            get {
                return ResourceManager.GetString("Till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an image to see a preview.
        /// </summary>
        public static string UploadImageHint {
            get {
                return ResourceManager.GetString("UploadImageHint", resourceCulture);
            }
        }
    }
}
