//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations.AnimalWorld {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnimalWorldZoo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimalWorldZoo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.AnimalWorld.AnimalWorldZoo", typeof(AnimalWorldZoo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of the zoo.
        /// </summary>
        public static string AddressExample {
            get {
                return ResourceManager.GetString("AddressExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add zoo.
        /// </summary>
        public static string AddZoo {
            get {
                return ResourceManager.GetString("AddZoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links between zoos and animal species.
        /// </summary>
        public static string AnimalSpeciesZoosLinks {
            get {
                return ResourceManager.GetString("AnimalSpeciesZoosLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a zoo.
        /// </summary>
        public static string ChooseZoo {
            get {
                return ResourceManager.GetString("ChooseZoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links setup.
        /// </summary>
        public static string LinksSetup {
            get {
                return ResourceManager.GetString("LinksSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data on zoos yet.
        /// </summary>
        public static string NoZoos {
            get {
                return ResourceManager.GetString("NoZoos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no zoos in the database..
        /// </summary>
        public static string NoZoosDb {
            get {
                return ResourceManager.GetString("NoZoosDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select a zoo, then an animal species.
        /// </summary>
        public static string SelectOrder {
            get {
                return ResourceManager.GetString("SelectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore Zoo.
        /// </summary>
        public static string ZooExample {
            get {
                return ResourceManager.GetString("ZooExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out the information about the new zoo.
        /// </summary>
        public static string ZooInfo {
            get {
                return ResourceManager.GetString("ZooInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the zoo.
        /// </summary>
        public static string ZooName {
            get {
                return ResourceManager.GetString("ZooName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is available.
        /// </summary>
        public static string ZooNameAvailable {
            get {
                return ResourceManager.GetString("ZooNameAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking availability....
        /// </summary>
        public static string ZooNameChecking {
            get {
                return ResourceManager.GetString("ZooNameChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already taken.
        /// </summary>
        public static string ZooNameTaken {
            get {
                return ResourceManager.GetString("ZooNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoos.
        /// </summary>
        public static string Zoos {
            get {
                return ResourceManager.GetString("Zoos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places where you can see amazing animals.
        /// </summary>
        public static string ZoosTitle {
            get {
                return ResourceManager.GetString("ZoosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the zoo.
        /// </summary>
        public static string ZooSummary {
            get {
                return ResourceManager.GetString("ZooSummary", resourceCulture);
            }
        }
    }
}
