// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebNet23Online.Data;

#nullable disable

namespace WebNet23Online.Data.Migrations
{
    [DbContext(typeof(WebContext))]
    [Migration("20260708182055_firststep111111")]
    partial class firststep111111
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimalSpeciesDataZooData", b =>
                {
                    b.Property<int>("AnimalSpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("ZooDataId")
                        .HasColumnType("int");

                    b.HasKey("AnimalSpeciesId", "ZooDataId");

                    b.HasIndex("ZooDataId");

                    b.ToTable("BindZooAndAnimalSpecies", (string)null);
                });

            modelBuilder.Entity("AnimeDataAnimeGirlData", b =>
                {
                    b.Property<int>("AnimesId")
                        .HasColumnType("int");

                    b.Property<int>("HeroesId")
                        .HasColumnType("int");

                    b.HasKey("AnimesId", "HeroesId");

                    b.HasIndex("HeroesId");

                    b.ToTable("AnimeDataAnimeGirlData");
                });

            modelBuilder.Entity("FoodItemDataOrderData", b =>
                {
                    b.Property<int>("FoodItemsId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.HasKey("FoodItemsId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("FoodItemDataOrderData");
                });

            modelBuilder.Entity("GameDataGameGenreData", b =>
                {
                    b.Property<int>("GameGenresId")
                        .HasColumnType("int");

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.HasKey("GameGenresId", "GamesId");

                    b.HasIndex("GamesId");

                    b.ToTable("GameDataGameGenreData");
                });

            modelBuilder.Entity("UserDataUserData", b =>
                {
                    b.Property<int>("MyFriendsId")
                        .HasColumnType("int");

                    b.Property<int>("WhoIsMyFriendsId")
                        .HasColumnType("int");

                    b.HasKey("MyFriendsId", "WhoIsMyFriendsId");

                    b.HasIndex("WhoIsMyFriendsId");

                    b.ToTable("UserDataUserData");
                });

            modelBuilder.Entity("WebNet23Online.Data.DataModels.FoodItemIngredientData", b =>
                {
                    b.Property<int>("FoodItemDataId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientDataId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityOfIngredients")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(10m);

                    b.HasKey("FoodItemDataId", "IngredientDataId");

                    b.HasIndex("IngredientDataId");

                    b.ToTable("FoodItemIngredientDatas", (string)null);
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimalWorld.AnimalFamilyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnimalFamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AnimalFamilies");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimalWorld.AnimalSpeciesData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalFamilyId")
                        .HasColumnType("int");

                    b.Property<string>("AnimalSpeciesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnimalSpeciesUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NativeRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalFamilyId");

                    b.HasIndex("UserId");

                    b.ToTable("AnimalSpecies");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimalWorld.PromotionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ZooId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimalWorld.ZooData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZooName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Zoos");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimeGirlData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnimeGirls");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimeStudioData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnimeStudios");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.CommentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CommentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ZooId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.FoodItemData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuDataId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("MenuDataId");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.GenreOfRockBandsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RockBandGenresDictionary");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MonthGoal")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitDoneDatesData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfCompletion")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.ToTable("HabitDoneDates");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitTrackerDiaryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DiaryEntries");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitTrackerProfileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("HabitTrackerProfile");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.IngredientData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.JdmCarsBlogCommentsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostsId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostsId");

                    b.HasIndex("UserId");

                    b.ToTable("JdmCarsBlogComments");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.JdmCarsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int?>("JdmManufacturerDataId")
                        .HasColumnType("int");

                    b.Property<string>("ManufacturerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleInspectionHistoryUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("JdmManufacturerDataId");

                    b.ToTable("JdmCars");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.JdmManufacturerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ManufacturerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JdmManufacturer");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.JdmPostsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlPicture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JdmPosts");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.LittleLemonData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailableTimesOnly")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CakePhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("Occasion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReservationDateOnly")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatingPreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GuestId");

                    b.ToTable("LittleLemon");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.LittleLemonGuestData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LittleLemonGuests");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.MazeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MazeType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mazes");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.MenuData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.NotificationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeToPublish")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.OrderData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockBandGenreData", b =>
                {
                    b.Property<int>("RockBandId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("RockBandId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("RockBandGenres");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockBandLikeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RockBandId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RockBandId");

                    b.HasIndex("UserId", "RockBandId")
                        .IsUnique();

                    b.ToTable("RockBandLikes");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockBandsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("RockBand");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockLegendsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<int?>("RockLegendsGenresId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RockLegendsGenresId");

                    b.ToTable("RockLegends");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockLegendsGenres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RockLegendsGenres");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.SlayTheSpire2HeroesCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManaCost")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Upgraded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HeroId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("SlayTheSpire2HeroesCards");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.SlayTheSpire2HeroesData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SlayTheSpire2Heroes");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.Steam.CommunityChatMessageData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CommunityChatMessages");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.Steam.GameData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageRating")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("PositiveReviewsCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewsCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.Steam.GameGenreData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.Steam.GameReviewData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GameId");

                    b.ToTable("GameReviews");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.Steam.PublisherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.TicketData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketType")
                        .HasColumnType("int");

                    b.Property<string>("UniqueKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ZooId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobilephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasFilter("[UserProfileId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserProfileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavBook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfileData");
                });

            modelBuilder.Entity("AnimalSpeciesDataZooData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.AnimalWorld.AnimalSpeciesData", null)
                        .WithMany()
                        .HasForeignKey("AnimalSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.AnimalWorld.ZooData", null)
                        .WithMany()
                        .HasForeignKey("ZooDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeDataAnimeGirlData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.AnimeData", null)
                        .WithMany()
                        .HasForeignKey("AnimesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.AnimeGirlData", null)
                        .WithMany()
                        .HasForeignKey("HeroesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodItemDataOrderData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.FoodItemData", null)
                        .WithMany()
                        .HasForeignKey("FoodItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.OrderData", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDataGameGenreData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.Steam.GameGenreData", null)
                        .WithMany()
                        .HasForeignKey("GameGenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.Steam.GameData", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserDataUserData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", null)
                        .WithMany()
                        .HasForeignKey("MyFriendsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.UserData", null)
                        .WithMany()
                        .HasForeignKey("WhoIsMyFriendsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebNet23Online.Data.DataModels.FoodItemIngredientData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.FoodItemData", "FoodItemData")
                        .WithMany("FoodItemIngredientDatas")
                        .HasForeignKey("FoodItemDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.IngredientData", "IngredientData")
                        .WithMany("FoodItemIngredientDatas")
                        .HasForeignKey("IngredientDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItemData");

                    b.Navigation("IngredientData");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimalWorld.AnimalFamilyData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Creator")
                        .WithMany("CreatedByMeAnimalFamilies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimalWorld.AnimalSpeciesData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.AnimalWorld.AnimalFamilyData", "AnimalFamily")
                        .WithMany("Species")
                        .HasForeignKey("AnimalFamilyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.UserData", "Creator")
                        .WithMany("CreatedByMeAnimalSpecies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AnimalFamily");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimalWorld.PromotionData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Creator")
                        .WithMany("Promotions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.AnimalWorld.ZooData", "Venue")
                        .WithMany("Promotions")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimalWorld.ZooData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Creator")
                        .WithMany("CreatedByMeZoos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimeData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.AnimeStudioData", "Studio")
                        .WithMany("Animes")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.CommentData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Author")
                        .WithMany("MyComments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.AnimalWorld.ZooData", "Zoo")
                        .WithMany("Comments")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Author");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.FoodItemData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Creator")
                        .WithMany("CreatedFoodItems")
                        .HasForeignKey("CreatorId");

                    b.HasOne("WebNet23Online.Data.Models.MenuData", "MenuData")
                        .WithMany("FoodItems")
                        .HasForeignKey("MenuDataId");

                    b.Navigation("Creator");

                    b.Navigation("MenuData");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "User")
                        .WithMany("Habits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitDoneDatesData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.HabitData", "Habit")
                        .WithMany("CompletedDates")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitTrackerDiaryData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "User")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitTrackerProfileData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "User")
                        .WithOne("HabitTrackerProfile")
                        .HasForeignKey("WebNet23Online.Data.Models.HabitTrackerProfileData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.IngredientData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Creator")
                        .WithMany("CreatedIngredients")
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.JdmCarsBlogCommentsData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.JdmPostsData", "Posts")
                        .WithMany("Comments")
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.UserData", "User")
                        .WithMany("JournalComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posts");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.JdmCarsData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Creator")
                        .WithMany("CreatedByCarsJdm")
                        .HasForeignKey("CreatorId");

                    b.HasOne("WebNet23Online.Data.Models.JdmManufacturerData", "JdmManufacturerData")
                        .WithMany("JdmCarsDatas")
                        .HasForeignKey("JdmManufacturerDataId");

                    b.Navigation("Creator");

                    b.Navigation("JdmManufacturerData");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.LittleLemonData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "CreatedByUser")
                        .WithMany("UserAccountLittleLemonReservations")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WebNet23Online.Data.Models.LittleLemonGuestData", "Guest")
                        .WithMany("GuestLittleLemonReservations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.MenuData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Creator")
                        .WithMany("CreatedMenus")
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.NotificationData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Author")
                        .WithMany("Notifications")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.OrderData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockBandGenreData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.GenreOfRockBandsData", "Genre")
                        .WithMany("RockBandGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.RockBandsData", "RockBand")
                        .WithMany("RockBandGenres")
                        .HasForeignKey("RockBandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("RockBand");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockBandLikeData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.RockBandsData", "RockBand")
                        .WithMany("RockBandLikes")
                        .HasForeignKey("RockBandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.UserData", "User")
                        .WithMany("RockBandLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RockBand");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockBandsData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "CreatedByUser")
                        .WithMany("RockBand")
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockLegendsData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.RockLegendsGenres", "Genres")
                        .WithMany("Groups")
                        .HasForeignKey("RockLegendsGenresId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.SlayTheSpire2HeroesCards", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "CreatedByUser")
                        .WithMany("CreatedSlayTheSpire2HeroesCards")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.SlayTheSpire2HeroesData", "Hero")
                        .WithMany("Cards")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.UserData", "ModifiedByUser")
                        .WithMany("ModifiedSlayTheSpire2HeroesCards")
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Hero");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.Steam.CommunityChatMessageData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "CreatedByUser")
                        .WithMany("CommunityChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.Steam.GameData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "CreatedByUser")
                        .WithMany("CreatedGames")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("WebNet23Online.Data.Models.UserData", "ModifiedByUser")
                        .WithMany("ModifiedGames")
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("WebNet23Online.Data.Models.Steam.PublisherData", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.Steam.GameReviewData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Author")
                        .WithMany("Reviews")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.Steam.GameData", "Game")
                        .WithMany("GameReviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.TicketData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "User")
                        .WithMany("MyTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.AnimalWorld.ZooData", "Zoo")
                        .WithMany("Tickets")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserProfileData", "UserProfile")
                        .WithOne("User")
                        .HasForeignKey("WebNet23Online.Data.Models.UserData", "UserProfileId");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimalWorld.AnimalFamilyData", b =>
                {
                    b.Navigation("Species");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimalWorld.ZooData", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Promotions");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.AnimeStudioData", b =>
                {
                    b.Navigation("Animes");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.FoodItemData", b =>
                {
                    b.Navigation("FoodItemIngredientDatas");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.GenreOfRockBandsData", b =>
                {
                    b.Navigation("RockBandGenres");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.HabitData", b =>
                {
                    b.Navigation("CompletedDates");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.IngredientData", b =>
                {
                    b.Navigation("FoodItemIngredientDatas");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.JdmManufacturerData", b =>
                {
                    b.Navigation("JdmCarsDatas");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.JdmPostsData", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.LittleLemonGuestData", b =>
                {
                    b.Navigation("GuestLittleLemonReservations");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.MenuData", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockBandsData", b =>
                {
                    b.Navigation("RockBandGenres");

                    b.Navigation("RockBandLikes");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.RockLegendsGenres", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.SlayTheSpire2HeroesData", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.Steam.GameData", b =>
                {
                    b.Navigation("GameReviews");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.Steam.PublisherData", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserData", b =>
                {
                    b.Navigation("CommunityChatMessages");

                    b.Navigation("CreatedByCarsJdm");

                    b.Navigation("CreatedByMeAnimalFamilies");

                    b.Navigation("CreatedByMeAnimalSpecies");

                    b.Navigation("CreatedByMeZoos");

                    b.Navigation("CreatedFoodItems");

                    b.Navigation("CreatedGames");

                    b.Navigation("CreatedIngredients");

                    b.Navigation("CreatedMenus");

                    b.Navigation("CreatedSlayTheSpire2HeroesCards");

                    b.Navigation("DiaryEntries");

                    b.Navigation("HabitTrackerProfile");

                    b.Navigation("Habits");

                    b.Navigation("JournalComments");

                    b.Navigation("ModifiedGames");

                    b.Navigation("ModifiedSlayTheSpire2HeroesCards");

                    b.Navigation("MyComments");

                    b.Navigation("MyTickets");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("Promotions");

                    b.Navigation("Reviews");

                    b.Navigation("RockBand");

                    b.Navigation("RockBandLikes");

                    b.Navigation("UserAccountLittleLemonReservations");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserProfileData", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
