// <auto-generated />
using System;
using AnimalWorld.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimalWorld.Data.Migrations
{
    [DbContext(typeof(WebContext))]
    [Migration("20260824191649_ChangeNullUserFields")]
    partial class ChangeNullUserFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimalSpeciesDataZooData", b =>
                {
                    b.Property<int>("AnimalSpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("animal_species_id");

                    b.Property<int>("ZoosId")
                        .HasColumnType("integer")
                        .HasColumnName("zoos_id");

                    b.HasKey("AnimalSpeciesId", "ZoosId")
                        .HasName("pk_zoo_species_bindings");

                    b.HasIndex("ZoosId")
                        .HasDatabaseName("ix_zoo_species_bindings_zoos_id");

                    b.ToTable("zoo_species_bindings", (string)null);
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Animals.AnimalFamilyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_animal_families");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_animal_families_creator_id");

                    b.ToTable("animal_families", (string)null);
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Animals.AnimalSpeciesData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalFamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("animal_family_id");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NativeRange")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("native_range");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_animal_species");

                    b.HasIndex("AnimalFamilyId")
                        .HasDatabaseName("ix_animal_species_animal_family_id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_animal_species_creator_id");

                    b.ToTable("animal_species", (string)null);
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Users.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Zoos.CommentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("ZooId")
                        .HasColumnType("integer")
                        .HasColumnName("zoo_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comments_author_id");

                    b.HasIndex("ZooId")
                        .HasDatabaseName("ix_comments_zoo_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Zoos.PromotionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_promotions");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_promotions_creator_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_promotions_venue_id");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Zoos.TicketData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("UniqueKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unique_key");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("ZooId")
                        .HasColumnType("integer")
                        .HasColumnName("zoo_id");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tickets_user_id");

                    b.HasIndex("ZooId")
                        .HasDatabaseName("ix_tickets_zoo_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Zoos.ZooData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_zoos");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_zoos_creator_id");

                    b.ToTable("zoos", (string)null);
                });

            modelBuilder.Entity("AnimalSpeciesDataZooData", b =>
                {
                    b.HasOne("AnimalWorld.Data.Models.Animals.AnimalSpeciesData", null)
                        .WithMany()
                        .HasForeignKey("AnimalSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zoo_species_bindings_animal_species_animal_species_id");

                    b.HasOne("AnimalWorld.Data.Models.Zoos.ZooData", null)
                        .WithMany()
                        .HasForeignKey("ZoosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zoo_species_bindings_zoos_zoos_id");
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Animals.AnimalFamilyData", b =>
                {
                    b.HasOne("AnimalWorld.Data.Models.Users.UserData", "Creator")
                        .WithMany("CreatedAnimalFamilies")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animal_families_users_creator_id");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Animals.AnimalSpeciesData", b =>
                {
                    b.HasOne("AnimalWorld.Data.Models.Animals.AnimalFamilyData", "AnimalFamily")
                        .WithMany("AnimalSpecies")
                        .HasForeignKey("AnimalFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animal_species_animal_families_animal_family_id");

                    b.HasOne("AnimalWorld.Data.Models.Users.UserData", "Creator")
                        .WithMany("CreatedAnimalSpecies")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animal_species_users_creator_id");

                    b.Navigation("AnimalFamily");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Zoos.CommentData", b =>
                {
                    b.HasOne("AnimalWorld.Data.Models.Users.UserData", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_author_id");

                    b.HasOne("AnimalWorld.Data.Models.Zoos.ZooData", "Zoo")
                        .WithMany("Comments")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_zoos_zoo_id");

                    b.Navigation("Author");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Zoos.PromotionData", b =>
                {
                    b.HasOne("AnimalWorld.Data.Models.Users.UserData", "Creator")
                        .WithMany("CreatedPromotions")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotions_users_creator_id");

                    b.HasOne("AnimalWorld.Data.Models.Zoos.ZooData", "Venue")
                        .WithMany("Promotions")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotions_zoos_venue_id");

                    b.Navigation("Creator");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Zoos.TicketData", b =>
                {
                    b.HasOne("AnimalWorld.Data.Models.Users.UserData", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_users_user_id");

                    b.HasOne("AnimalWorld.Data.Models.Zoos.ZooData", "Zoo")
                        .WithMany("Tickets")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_zoos_zoo_id");

                    b.Navigation("User");

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Zoos.ZooData", b =>
                {
                    b.HasOne("AnimalWorld.Data.Models.Users.UserData", "Creator")
                        .WithMany("CreatedZoos")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zoos_users_creator_id");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Animals.AnimalFamilyData", b =>
                {
                    b.Navigation("AnimalSpecies");
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Users.UserData", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CreatedAnimalFamilies");

                    b.Navigation("CreatedAnimalSpecies");

                    b.Navigation("CreatedPromotions");

                    b.Navigation("CreatedZoos");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AnimalWorld.Data.Models.Zoos.ZooData", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Promotions");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
