FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Net23Online/WebNet23Online/WebNet23Online.csproj", "Net23Online/WebNet23Online/"]
COPY ["Net23Online/WebNet23Online.Data/WebNet23Online.Data.csproj", "Net23Online/WebNet23Online.Data/"]
COPY ["Net23Online/MazeCore/MazeCore.csproj", "MazeCore/"]
RUN dotnet restore "./Net23Online/WebNet23Online/WebNet23Online.csproj"
COPY . .
WORKDIR "/src/Net23Online/WebNet23Online"
RUN dotnet build "./WebNet23Online.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./WebNet23Online.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebNet23Online.dll"]