<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>73b94761-958c-409b-b738-dae7cc66131f</UserSecretsId>
	</PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\japanese-domestic-market\history-inspection\" />
    <Folder Include="wwwroot\js\rock-band\" />
    <Folder Include="wwwroot\temp\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MazeCore\MazeCore.csproj" />
    <ProjectReference Include="..\WebNet23Online.Data\WebNet23Online.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\rock-bands\" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\steam\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localizations\AnimalWorld\AnimalWorldAddData.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AnimalWorldAddData.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\AnimalWorld\AnimalWorldAnimalFamily.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AnimalWorldAnimalFamily.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\AnimalWorld\AnimalWorldAnimalSpecies.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AnimalWorldAnimalSpecies.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\AnimalWorld\AnimalWorldComments.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AnimalWorldComments.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\AnimalWorld\AnimalWorldCommon.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AnimalWorldCommon.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\AnimalWorld\AnimalWorldFacts.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AnimalWorldFacts.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\AnimalWorld\AnimalWorldIndex.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AnimalWorldIndex.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\AnimalWorld\AnimalWorldPromotions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AnimalWorldPromotions.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\AnimalWorld\AnimalWorldReservations.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AnimalWorldReservations.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\AnimalWorld\AnimalWorldZoo.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AnimalWorldZoo.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\AnimeGirl.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AnimeGirl.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\DelightBistro.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DelightBistro.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\Home.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Home.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\SlayTheSpire2Index.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SlayTheSpire2Index.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\JapaneseDomesticMarket.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>JapaneseDomesticMarket.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\Steam\AddGamePage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AddGamePage.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\Steam\CatalogPage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CatalogPage.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\Steam\EditGamePage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EditGamePage.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\Steam\GameDetailsPage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GameDetailsPage.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\Steam\Mainpage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Mainpage.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\Steam\ProfilePage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProfilePage.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\Steam\SteamShared.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SteamShared.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\RockBand.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RockBand.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\RockLegendsPortal.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RockLegendsPortal.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\HabitTracker\HabitTracker.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HabitTracker.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localizations\AnimalWorld\AnimalWorldAddData.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AnimalWorldAddData.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\AnimalWorld\AnimalWorldAnimalFamily.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AnimalWorldAnimalFamily.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\AnimalWorld\AnimalWorldAnimalSpecies.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AnimalWorldAnimalSpecies.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\AnimalWorld\AnimalWorldComments.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AnimalWorldComments.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\AnimalWorld\AnimalWorldCommon.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AnimalWorldCommon.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\AnimalWorld\AnimalWorldFacts.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AnimalWorldFacts.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\AnimalWorld\AnimalWorldIndex.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AnimalWorldIndex.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\AnimalWorld\AnimalWorldPromotions.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AnimalWorldPromotions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\AnimalWorld\AnimalWorldReservations.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AnimalWorldReservations.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\AnimalWorld\AnimalWorldZoo.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AnimalWorldZoo.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\AnimeGirl.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AnimeGirl.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\DelightBistro.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DelightBistro.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\DelightBistro.Ru.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Home.De.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Home.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Home.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\JapaneseDomesticMarket.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>JapaneseDomesticMarket.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Resource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\DelightBistro.De.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\SlayTheSpire2Index.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SlayTheSpire2Index.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Steam\AddGamePage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AddGamePage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Steam\CatalogPage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CatalogPage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Steam\EditGamePage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>EditGamePage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Steam\GameDetailsPage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>GameDetailsPage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Steam\Mainpage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Mainpage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Steam\ProfilePage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ProfilePage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Steam\SteamShared.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SteamShared.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\RockBand.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>RockBand.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\RockLegendsPortal.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>RockLegendsPortal.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\HabitTracker\HabitTracker.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>HabitTracker.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.25">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.1" />
  </ItemGroup>

</Project>
