//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnimeGirl {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnimeGirl() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.AnimeGirl", typeof(AnimeGirl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string AnimeTableData_ColumnId {
            get {
                return ResourceManager.GetString("AnimeTableData_ColumnId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AnimeTableData_ColumnName {
            get {
                return ResourceManager.GetString("AnimeTableData_ColumnName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string AnimeTableData_ColumnUrl {
            get {
                return ResourceManager.GetString("AnimeTableData_ColumnUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Chat_Me {
            get {
                return ResourceManager.GetString("Chat_Me", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select characters on the page first.
        /// </summary>
        public static string Chat_SelectCharactersFirst {
            get {
                return ResourceManager.GetString("Chat_SelectCharactersFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} shared characters.
        /// </summary>
        public static string Chat_SharedByUser {
            get {
                return ResourceManager.GetString("Chat_SharedByUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You shared characters.
        /// </summary>
        public static string Chat_SharedByYou {
            get {
                return ResourceManager.GetString("Chat_SharedByYou", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} joined the chat.
        /// </summary>
        public static string Chat_UserJoined {
            get {
                return ResourceManager.GetString("Chat_UserJoined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} left the chat.
        /// </summary>
        public static string Chat_UserLeft {
            get {
                return ResourceManager.GetString("Chat_UserLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cover url.
        /// </summary>
        public static string CreateAnime_CoverUrlPlaceholder {
            get {
                return ResourceManager.GetString("CreateAnime_CoverUrlPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CreateAnime_NamePlaceholder {
            get {
                return ResourceManager.GetString("CreateAnime_NamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CreateAnime_Save {
            get {
                return ResourceManager.GetString("CreateAnime_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string CreateGirl_CharacterAlt {
            get {
                return ResourceManager.GetString("CreateGirl_CharacterAlt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CreateGirl_DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("CreateGirl_DescriptionPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name again.
        /// </summary>
        public static string CreateGirl_NameAgainPlaceholder {
            get {
                return ResourceManager.GetString("CreateGirl_NameAgainPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CreateGirl_NamePlaceholder {
            get {
                return ResourceManager.GetString("CreateGirl_NamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string CreateGirl_Or {
            get {
                return ResourceManager.GetString("CreateGirl_Or", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CreateGirl_Save {
            get {
                return ResourceManager.GetString("CreateGirl_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string CreateGirl_SizePlaceholder {
            get {
                return ResourceManager.GetString("CreateGirl_SizePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string CreateGirl_UrlPlaceholder {
            get {
                return ResourceManager.GetString("CreateGirl_UrlPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add game.
        /// </summary>
        public static string Handmade_AddGame {
            get {
                return ResourceManager.GetString("Handmade_AddGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Anime 1.
        /// </summary>
        public static string Handmade_AnimeSample {
            get {
                return ResourceManager.GetString("Handmade_AnimeSample", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Books info.
        /// </summary>
        public static string Handmade_BooksInfo {
            get {
                return ResourceManager.GetString("Handmade_BooksInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Girl.
        /// </summary>
        public static string Handmade_CharacterFemale {
            get {
                return ResourceManager.GetString("Handmade_CharacterFemale", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Boy.
        /// </summary>
        public static string Handmade_CharacterMale {
            get {
                return ResourceManager.GetString("Handmade_CharacterMale", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rob banks.
        /// </summary>
        public static string Handmade_FeatureRobBanks {
            get {
                return ResourceManager.GetString("Handmade_FeatureRobBanks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rob the king.
        /// </summary>
        public static string Handmade_FeatureRobKing {
            get {
                return ResourceManager.GetString("Handmade_FeatureRobKing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rob shops.
        /// </summary>
        public static string Handmade_FeatureRobShops {
            get {
                return ResourceManager.GetString("Handmade_FeatureRobShops", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Game name.
        /// </summary>
        public static string Handmade_GameNamePlaceholder {
            get {
                return ResourceManager.GetString("Handmade_GameNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, now is {1}:{2}.
        /// </summary>
        public static string Handmade_Hello {
            get {
                return ResourceManager.GetString("Handmade_Hello", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nice.
        /// </summary>
        public static string Handmade_Nice {
            get {
                return ResourceManager.GetString("Handmade_Nice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Smile Generator 1.
        /// </summary>
        public static string Handmade_SmileGenerator1 {
            get {
                return ResourceManager.GetString("Handmade_SmileGenerator1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Smile Generator 2.
        /// </summary>
        public static string Handmade_SmileGenerator2 {
            get {
                return ResourceManager.GetString("Handmade_SmileGenerator2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Smile Generator 3.
        /// </summary>
        public static string Handmade_SmileGenerator3 {
            get {
                return ResourceManager.GetString("Handmade_SmileGenerator3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cover:.
        /// </summary>
        public static string Index_AnimeCatalog_CoverAlt {
            get {
                return ResourceManager.GetString("Index_AnimeCatalog_CoverAlt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Covers and titles — what's already in the collection..
        /// </summary>
        public static string Index_AnimeCatalog_Intro {
            get {
                return ResourceManager.GetString("Index_AnimeCatalog_Intro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Anime catalog.
        /// </summary>
        public static string Index_AnimeCatalog_Title {
            get {
                return ResourceManager.GetString("Index_AnimeCatalog_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Books worth rereading and recommending will show up here..
        /// </summary>
        public static string Index_Books_Placeholder {
            get {
                return ResourceManager.GetString("Index_Books_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Index_Books_Title {
            get {
                return ResourceManager.GetString("Index_Books_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        public static string Index_Cat_Alt {
            get {
                return ResourceManager.GetString("Index_Cat_Alt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cats.
        /// </summary>
        public static string Index_Cats_Title {
            get {
                return ResourceManager.GetString("Index_Cats_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close chat.
        /// </summary>
        public static string Index_Chat_CloseAria {
            get {
                return ResourceManager.GetString("Index_Chat_CloseAria", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message….
        /// </summary>
        public static string Index_Chat_MessagePlaceholder {
            get {
                return ResourceManager.GetString("Index_Chat_MessagePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open chat.
        /// </summary>
        public static string Index_Chat_OpenAria {
            get {
                return ResourceManager.GetString("Index_Chat_OpenAria", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Index_Chat_PanelAria {
            get {
                return ResourceManager.GetString("Index_Chat_PanelAria", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Index_Chat_Send {
            get {
                return ResourceManager.GetString("Index_Chat_Send", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Index_Chat_Share {
            get {
                return ResourceManager.GetString("Index_Chat_Share", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Index_Chat_Title {
            get {
                return ResourceManager.GetString("Index_Chat_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You:.
        /// </summary>
        public static string Index_Chat_UserLabel {
            get {
                return ResourceManager.GetString("Index_Chat_UserLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Made with warmth · 2026.
        /// </summary>
        public static string Index_Footer {
            get {
                return ResourceManager.GetString("Index_Footer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A random joke, waifu and cats — loaded fresh every time you open the page..
        /// </summary>
        public static string Index_FunSection_Intro {
            get {
                return ResourceManager.GetString("Index_FunSection_Intro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A bit of positivity.
        /// </summary>
        public static string Index_FunSection_Title {
            get {
                return ResourceManager.GetString("Index_FunSection_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to I'll add a list of favorite games and maybe a few screenshots soon..
        /// </summary>
        public static string Index_Games_Placeholder {
            get {
                return ResourceManager.GetString("Index_Games_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Index_Games_Title {
            get {
                return ResourceManager.GetString("Index_Games_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Anime, games and books.
        /// </summary>
        public static string Index_Header {
            get {
                return ResourceManager.GetString("Index_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Personal page.
        /// </summary>
        public static string Index_Header_TagLine {
            get {
                return ResourceManager.GetString("Index_Header_TagLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string Index_Hero_Alt {
            get {
                return ResourceManager.GetString("Index_Hero_Alt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Index_Heroes_Delete {
            get {
                return ResourceManager.GetString("Index_Heroes_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Illustrations and anime where the character appears in the hero list..
        /// </summary>
        public static string Index_Heroes_Intro {
            get {
                return ResourceManager.GetString("Index_Heroes_Intro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likes:.
        /// </summary>
        public static string Index_Heroes_Likes {
            get {
                return ResourceManager.GetString("Index_Heroes_Likes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string Index_Heroes_Next {
            get {
                return ResourceManager.GetString("Index_Heroes_Next", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Index_Heroes_PageSize_All {
            get {
                return ResourceManager.GetString("Index_Heroes_PageSize_All", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show per page:.
        /// </summary>
        public static string Index_Heroes_PageSize_Label {
            get {
                return ResourceManager.GetString("Index_Heroes_PageSize_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Characters per page.
        /// </summary>
        public static string Index_Heroes_PageSize_Aria {
            get {
                return ResourceManager.GetString("Index_Heroes_PageSize_Aria", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Character pages.
        /// </summary>
        public static string Index_Heroes_Pagination_Aria {
            get {
                return ResourceManager.GetString("Index_Heroes_Pagination_Aria", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string Index_Heroes_Prev {
            get {
                return ResourceManager.GetString("Index_Heroes_Prev", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Index_Heroes_Remove {
            get {
                return ResourceManager.GetString("Index_Heroes_Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Index_Heroes_Title {
            get {
                return ResourceManager.GetString("Index_Heroes_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Joke of the day.
        /// </summary>
        public static string Index_Joke_Title {
            get {
                return ResourceManager.GetString("Index_Joke_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Here I collect things I like: anime in detail for now — games and books will come later..
        /// </summary>
        public static string Index_Lead {
            get {
                return ResourceManager.GetString("Index_Lead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MORE.
        /// </summary>
        public static string Index_LinkMore {
            get {
                return ResourceManager.GetString("Index_LinkMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The only one.
        /// </summary>
        public static string Index_LinkOnlyOne {
            get {
                return ResourceManager.GetString("Index_LinkOnlyOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Anime.
        /// </summary>
        public static string Index_LinkSection_AnimeLabel {
            get {
                return ResourceManager.GetString("Index_LinkSection_AnimeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Index_LinkSection_Button {
            get {
                return ResourceManager.GetString("Index_LinkSection_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Anime and character selection.
        /// </summary>
        public static string Index_LinkSection_GroupLabel {
            get {
                return ResourceManager.GetString("Index_LinkSection_GroupLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string Index_LinkSection_HeroLabel {
            get {
                return ResourceManager.GetString("Index_LinkSection_HeroLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pick an anime and a character — saving the link will be wired up later..
        /// </summary>
        public static string Index_LinkSection_Intro {
            get {
                return ResourceManager.GetString("Index_LinkSection_Intro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select anime.
        /// </summary>
        public static string Index_LinkSection_SelectAnime {
            get {
                return ResourceManager.GetString("Index_LinkSection_SelectAnime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select character.
        /// </summary>
        public static string Index_LinkSection_SelectHero {
            get {
                return ResourceManager.GetString("Index_LinkSection_SelectHero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Link character to anime.
        /// </summary>
        public static string Index_LinkSection_Title {
            get {
                return ResourceManager.GetString("Index_LinkSection_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Two is enough.
        /// </summary>
        public static string Index_LinkTwoEnough {
            get {
                return ResourceManager.GetString("Index_LinkTwoEnough", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create movie.
        /// </summary>
        public static string Index_MovieCatalog_CreateButton {
            get {
                return ResourceManager.GetString("Index_MovieCatalog_CreateButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Covers and titles — what's already in the collection..
        /// </summary>
        public static string Index_MovieCatalog_Intro {
            get {
                return ResourceManager.GetString("Index_MovieCatalog_Intro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Movie name.
        /// </summary>
        public static string Index_MovieCatalog_NamePlaceholder {
            get {
                return ResourceManager.GetString("Index_MovieCatalog_NamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Movie catalog.
        /// </summary>
        public static string Index_MovieCatalog_Title {
            get {
                return ResourceManager.GetString("Index_MovieCatalog_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Movie cover url.
        /// </summary>
        public static string Index_MovieCatalog_UrlPlaceholder {
            get {
                return ResourceManager.GetString("Index_MovieCatalog_UrlPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My hobbies — anime, games, books.
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waifu illustration.
        /// </summary>
        public static string Index_Waifu_Alt {
            get {
                return ResourceManager.GetString("Index_Waifu_Alt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open original.
        /// </summary>
        public static string Index_Waifu_OpenOriginal {
            get {
                return ResourceManager.GetString("Index_Waifu_OpenOriginal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waifu.
        /// </summary>
        public static string Index_Waifu_Title {
            get {
                return ResourceManager.GetString("Index_Waifu_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Anime table.
        /// </summary>
        public static string Nav_AnimeTableData {
            get {
                return ResourceManager.GetString("Nav_AnimeTableData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create anime.
        /// </summary>
        public static string Nav_CreateAnime {
            get {
                return ResourceManager.GetString("Nav_CreateAnime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create character.
        /// </summary>
        public static string Nav_CreateGirl {
            get {
                return ResourceManager.GetString("Nav_CreateGirl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Handmade.
        /// </summary>
        public static string Nav_HandMade {
            get {
                return ResourceManager.GetString("Nav_HandMade", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nice.
        /// </summary>
        public static string Nav_Nice {
            get {
                return ResourceManager.GetString("Nav_Nice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Character table.
        /// </summary>
        public static string Nav_TableData {
            get {
                return ResourceManager.GetString("Nav_TableData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        public static string Nav_ToggleNavigation {
            get {
                return ResourceManager.GetString("Nav_ToggleNavigation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New anime name:.
        /// </summary>
        public static string Notification_NewAnime {
            get {
                return ResourceManager.GetString("Notification_NewAnime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected anime titles.
        /// </summary>
        public static string TableData_ColumnConnectedAnime {
            get {
                return ResourceManager.GetString("TableData_ColumnConnectedAnime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string TableData_ColumnId {
            get {
                return ResourceManager.GetString("TableData_ColumnId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TableData_ColumnTitle {
            get {
                return ResourceManager.GetString("TableData_ColumnTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string TableData_ColumnUrl {
            get {
                return ResourceManager.GetString("TableData_ColumnUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ==.
        /// </summary>
        public static string TableData_FilterEqual {
            get {
                return ResourceManager.GetString("TableData_FilterEqual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string TableData_FilterLess {
            get {
                return ResourceManager.GetString("TableData_FilterLess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string TableData_FilterMore {
            get {
                return ResourceManager.GetString("TableData_FilterMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter value.
        /// </summary>
        public static string TableData_FilterValuePlaceholder {
            get {
                return ResourceManager.GetString("TableData_FilterValuePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No filter.
        /// </summary>
        public static string TableData_NoFilter {
            get {
                return ResourceManager.GetString("TableData_NoFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name is already used.
        /// </summary>
        public static string Validation_NameAlreadyUsed {
            get {
                return ResourceManager.GetString("Validation_NameAlreadyUsed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        public static string Validation_NameRequired {
            get {
                return ResourceManager.GetString("Validation_NameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name and confirmation must match.
        /// </summary>
        public static string Validation_NamesMustMatch {
            get {
                return ResourceManager.GetString("Validation_NamesMustMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Size must be between 1 and 5.
        /// </summary>
        public static string Validation_SizeRange {
            get {
                return ResourceManager.GetString("Validation_SizeRange", resourceCulture);
            }
        }
    }
}
